"use strict";

import { parseAllTagsJson, TagEntry } from './tiff-tag-utils.js';

/**
 * Fast TIFF Processor using WebAssembly
 *
 * This module provides a high-performance TIFF decoder using Rust/WebAssembly.
 * It can be used as a drop-in replacement for geotiff.js for faster loading.
 */

let wasmModule: any = null;
let wasmInitPromise: Promise<any> | null = null;

/**
 * Initialize the WASM module
 */
async function initWasm(): Promise<any> {
    if (wasmModule) {
        return wasmModule;
    }

    if (wasmInitPromise) {
        return wasmInitPromise;
    }

    wasmInitPromise = (async () => {
        try {
            // Import the JS bindings generated by wasm-pack
            // Use relative path for VS Code webview compatibility
            const wasmBindingsPath: string = ('../wasm/tiff-wasm.js');
            const { default: init, decode_tiff, decode_tiff_page, tiff_page_count, extract_exif_tags } = await import(wasmBindingsPath);

            // Initialize the WASM module
            await init();

            wasmModule = { decode_tiff, decode_tiff_page, tiff_page_count, extract_exif_tags };
            return wasmModule;
        } catch (error) {
            console.warn('Failed to load WASM module, will use geotiff.js fallback:', error);
            return null;
        }
    })();

    return wasmInitPromise;
}

export interface TiffDecodeResult {
	pageIndex: number;
	pageCount: number;
    width: number;
    height: number;
    channels: number;
    bitsPerSample: number;
    /** 1=uint, 2=int, 3=float */
    sampleFormat: number;
    /** TIFF compression type */
    compression: number;
    /** TIFF predictor value */
    predictor: number;
    /** TIFF photometric interpretation */
    photometricInterpretation: number;
    /** TIFF planar configuration */
    planarConfiguration: number;
    rowsPerStrip?: number;
    stripCount?: number;
    stripByteCountTotal?: number;
    stripByteCountMax?: number;
    tileWidth?: number;
    tileLength?: number;
    tileCount?: number;
    directDecode?: boolean;
    /** Pixel data as floats */
    data: Float32Array;
    /** Minimum value */
    min: number;
    /** Maximum value */
    max: number;
    /** JSON array of every tag found in the file (TIFF/Exif/GPS), see tiff-tag-utils.js */
    allTagsJson: string;
}

/**
 * Fast TIFF Processor class using WASM
 */
export class TiffWasmProcessor {
    wasm: any;

    constructor() {
        this.wasm = null;
    }

    /**
     * Initialize the WASM module
     * @returns True if WASM loaded, false if falling back to JS
     */
    async init(): Promise<boolean> {
        this.wasm = await initWasm();
        return this.wasm !== null;
    }

    /**
     * Check if WASM is available
     */
    isAvailable(): boolean {
        return this.wasm !== null;
    }

    /**
     * Decode a TIFF file from an ArrayBuffer
     * @param buffer - TIFF file data
     */
    async decode(buffer: ArrayBuffer, pageIndex = 0): Promise<TiffDecodeResult> {
        if (!this.wasm) {
            throw new Error('WASM not initialized. Call init() first.');
        }

        const uint8Array = new Uint8Array(buffer);
        const pageCount = typeof this.wasm.tiff_page_count === 'function'
            ? this.wasm.tiff_page_count(uint8Array)
            : 1;
        if (pageIndex < 0 || pageIndex >= pageCount) {
            throw new Error(`TIFF page index ${pageIndex} is out of range (page count: ${pageCount})`);
        }
        const result = pageIndex > 0 && typeof this.wasm.decode_tiff_page === 'function'
            ? this.wasm.decode_tiff_page(uint8Array, pageIndex)
            : this.wasm.decode_tiff(uint8Array);

        const decodeResult: TiffDecodeResult = {
			pageIndex,
			pageCount,
            width: result.width,
            height: result.height,
            channels: result.channels,
            bitsPerSample: result.bits_per_sample,
            sampleFormat: result.sample_format,
            compression: result.compression,
            predictor: result.predictor,
            photometricInterpretation: result.photometric_interpretation,
            planarConfiguration: result.planar_configuration,
            rowsPerStrip: result.rows_per_strip,
            stripCount: result.strip_count,
            stripByteCountTotal: Number(result.strip_byte_count_total || 0),
            stripByteCountMax: Number(result.strip_byte_count_max || 0),
            tileWidth: result.tile_width,
            tileLength: result.tile_length,
            tileCount: result.tile_count,
            directDecode: result.direct_decode,
            data: new Float32Array(result.get_data_as_f32()),
            min: result.min_value,
            max: result.max_value,
            allTagsJson: result.all_tags_json
        };

        return decodeResult;
    }
}

/**
 * Walk a raw TIFF-structured Exif blob (e.g. a JPEG APP1 payload with its
 * "Exif\0\0" prefix already stripped, or a PNG eXIf chunk's raw bytes) and
 * return every tag found, in the same shape as TIFF's own tag dump. Lazily
 * loads/reuses the same WASM module as TiffWasmProcessor.
 */
export async function extractExifTagsFromBlob(blob: Uint8Array): Promise<TagEntry[]> {
    const wasm = await initWasm();
    if (!wasm || typeof wasm.extract_exif_tags !== 'function') { return []; }
    try {
        return parseAllTagsJson(wasm.extract_exif_tags(blob));
    } catch (error) {
        console.warn('[extractExifTagsFromBlob] Failed to parse embedded Exif blob:', error);
        return [];
    }
}

// Export for use
export { initWasm };
