// Ambient module declarations for vendored/generated browser assets that ship
// as plain (non-TypeScript) files under media/ — bundled third-party scripts
// copied in at build time (geotiff.min.js, upng.min.js) and the WASM glue
// module generated by wasm-pack (media/wasm/tiff-wasm.js, only present after
// `npm run build:wasm`). None of these have real type information; treat
// their exports as `any` so importing files can still be typechecked.
declare module '*.min.js' {
    const value: any;
    export = value;
}

declare module '*/wasm/tiff-wasm.js' {
    const initTiffWasm: any;
    export default initTiffWasm;
    export const decode_czi_fast: any;
    export const decode_nd2_fast: any;
    export const decode_lif_fast: any;
    export const decode_sdt_fast: any;
    export const decode_dicom_fast: any;
    export const label_components_fast: any;
    export const subtract_background_fast: any;
    export const gaussian_blur_fast: any;
    export const distance_transform_fast: any;
    export const fill_mask_holes_fast: any;
    export const build_histogram_fast: any;
    export const auto_threshold_bin_fast: any;
    export const global_threshold_mask_fast: any;
    export const local_threshold_mask_fast: any;
    export const local_auto_threshold_mask_fast: any;
    export const compute_stability_curve_fast: any;
    export const demosaic: any;
    export const extract_exif_tags: any;
    export const decode_exr_fast: any;
    export const decode_fits_fast: any;
    export const decode_hdr_fast: any;
    export const decode_jpeg_fast: any;
    export const decode_netcdf_fast: any;
    export const decode_npy_fast: any;
    export const decode_npy_display_fast: any;
    export const decode_pfm_fast: any;
    export const decode_pfm_display_fast: any;
    export const decode_png16_fast: any;
    export const decode_ppm_fast: any;
    export const decode_ppm_display_fast: any;
    export const RgbaLayerCompositor: any;
    export const decode_tiff: any;
    export const decode_tiff_fast: any;
	export const decode_tiff_page: any;
	export const decode_tiff_page_fast: any;
	export const tiff_page_count: any;
	export const tiff_page_directory: any;
	export const remote_tiff_header: any;
	export const remote_tiff_ifd: any;
	export const remote_tiff_index_values: any;
	export const decode_tiff_region: any;
	export const decode_tiff_preview: any;
	export const tiff_preview_reduction: any;
	export class TiffRegionDecoder {
		constructor(data: Uint8Array);
		decode(pageIndex: number, x: number, y: number, width: number, height: number): any;
		free(): void;
	}
	export const tiff_region_decode_available: any;
	export const tiff_float_strip_plan: any;
	export const exr_zip_f32_plan: any;
	export const decode_exr_zip_f32_blocks: any;
	export const tiff_strip_metadata: any;
	export const compute_image_stats_f32: any;
	export const compute_image_stats_u8: any;
	export const compute_image_stats_u16: any;
}

// The JPEG XL decoder is a SEPARATE wasm-pack module (media/wasm/jxl-wasm.js),
// built by `npm run build:wasm:jxl`. It is imported statically so esbuild
// inlines the glue, but its ~2.2 MB payload is only fetched when `init` is
// called for standalone or TIFF/DICOM-embedded JPEG XL.
declare module '*/wasm/jxl-wasm.js' {
    const initJxlWasm: any;
    export default initJxlWasm;
    export const decode_jxl_fast: any;
    export const decode_dicom_fast: any;
    export const decode_tiff: any;
    export const decode_tiff_fast: any;
    export const decode_tiff_page: any;
    export const decode_tiff_page_fast: any;
    export const tiff_page_count: any;
}

// The heavy-codec module (media/wasm/codec-wasm.js), built by
// `npm run build:wasm:codecs` from the SAME adapter as tiff-wasm with the
// `heavy-codecs` feature on. Its exports are a superset of the core module's;
// only the ones the fallback dispatch uses are declared here.
declare module '*/wasm/codec-wasm.js' {
    const initCodecWasm: any;
    export default initCodecWasm;
    export const decode_tiff: any;
    export const decode_tiff_fast: any;
    export const decode_tiff_page: any;
    export const decode_tiff_page_fast: any;
    export const tiff_page_count: any;
    export const tiff_page_directory: any;
	export const remote_tiff_header: any;
	export const remote_tiff_ifd: any;
	export const remote_tiff_index_values: any;
    export const decode_dicom_fast: any;
    export const decode_jpeg2000_fast: any;
    export const decode_czi_fast: any;
    export const decode_jpegxr_fast: any;
}
