// Ambient module declarations for vendored/generated browser assets that ship
// as plain (non-TypeScript) files under media/ — bundled third-party scripts
// copied in at build time (geotiff.min.js, upng.min.js) and the WASM glue
// module generated by wasm-pack (media/wasm/tiff-wasm.js, only present after
// `npm run build:wasm`). None of these have real type information; treat
// their exports as `any` so importing files can still be typechecked.
declare module '*.min.js' {
    const value: any;
    export = value;
}

declare module '*/wasm/tiff-wasm.js' {
    const initTiffWasm: any;
    export default initTiffWasm;
    export const decode_czi_fast: any;
    export const decode_dicom_fast: any;
    export const demosaic: any;
    export const extract_exif_tags: any;
    export const decode_exr_fast: any;
    export const decode_fits_fast: any;
    export const decode_hdr_fast: any;
    export const decode_jpeg_fast: any;
    export const decode_netcdf_fast: any;
    export const decode_npy_fast: any;
    export const decode_pfm_fast: any;
    export const decode_png16_fast: any;
    export const decode_ppm_fast: any;
    export const RgbaLayerCompositor: any;
    export const decode_tiff: any;
    export const decode_tiff_fast: any;
	export const decode_tiff_page: any;
	export const decode_tiff_page_fast: any;
	export const tiff_page_count: any;
	export const compute_image_stats_f32: any;
	export const compute_image_stats_u8: any;
	export const compute_image_stats_u16: any;
}
