// Ambient module declarations for vendored/generated browser assets that ship
// as plain (non-TypeScript) files under media/ — bundled third-party scripts
// copied in at build time (geotiff.min.js, upng.min.js) and the WASM glue
// module generated by wasm-pack (media/wasm/tiff-wasm.js, only present after
// `npm run build:wasm`). None of these have real type information; treat
// their exports as `any` so importing files can still be typechecked.
declare module '*.min.js' {
    const value: any;
    export = value;
}

declare module '*/wasm/tiff-wasm.js' {
    const initTiffWasm: any;
    export default initTiffWasm;
    export const decode_exr_fast: any;
    export const decode_hdr_fast: any;
    export const decode_png16_fast: any;
    export const decode_tiff: any;
    export const decode_tiff_fast: any;
}
